version: '3.9'
services:
  db:
    image: mariadb:latest
    restart: on-failure
    environment:
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: dev
    volumes:
      - data:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    ports:
      - 3306:3306
  nginx:
    image: nginx:latest
    volumes:
      - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html/app:rw,cached
    ports:
      - 80:80
      - 443:443
  php:
    image: mceikens/php-dev:7.2-latest
    working_dir: /usr/share/nginx/html/app
    privileged: true
    volumes:
      - ./:/usr/share/nginx/html/app:rw,cached
  maildev:
    image: maildev/maildev:latest
    ports:
      - 8080:80
volumes:
  data:
